<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>FS, APP</title>
    <style>
        .container .row .col{
            width: 33%;
            height: 33%;
            overflow: hidden;
        }
    </style>
</head>
    <body>

    <div class="container">
        <div class="container">
            <nav class="nav">
                <a class="nav-link active" href="#">Active</a>
                <a class="nav-link" href="#">Link</a>
                <a class="nav-link" href="#">Link</a>
                <a class="nav-link disabled" href="#">Disabled</a>
            </nav>

            <form>
                <div class="form-row">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Chapeu">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-2">Buscar</button>
                    </div>
                </div>
            </form>
            <div style="width: 100%; border: 1px black; overflow: hidden">
            <?php foreach($instagram['data'] as $each) : ?>
                <div class="col" style="float: left; width: 33%;; padding: 15px" data-toggle="tooltip" data-placement="top" title="<?=$each['getCaption']?>">
                    <img src="<?=$each['getImageThumbnailUrl']?>" style="width: 100%">
                    <?=$each['getCreatedTime']?>
                </div>
            <?php endforeach; ?>
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="javascript:history.back()">Previous</a></li>
                    <?php if($instagram['hasNextPage']) : ?>
                        <li class="page-item"><a class="page-link" href="./<?=$instagram['maxId']?>">Next</a></li>
                    <?php endif;?>
                </ul>
            </nav>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>

    <script>
        $('.col').tooltip({ boundary: 'window' })
    </script>
</html>